//
// Created by fleur on 14/11/2021.
//

#ifndef GOLPHOOK_FUN_DISPATCHUSERMESSAGE_HH
#define GOLPHOOK_FUN_DISPATCHUSERMESSAGE_HH


class DispatchUserMessage {

};


#endif //GOLPHOOK_FUN_DISPATCHUSERMESSAGE_HH
