//
// Created by fleur on 14/11/2021.
//

#ifndef GOLPHOOK_FUN_INTERFACESCOLLECTION_HH
#define GOLPHOOK_FUN_INTERFACESCOLLECTION_HH


class InterfacesCollection {

};


#endif //GOLPHOOK_FUN_INTERFACESCOLLECTION_HH
