//
// Created by fleur on 14/11/2021.
//

#ifndef GOLPHOOK_FUN_DRAWITEMSCOLLECTION_HH
#define GOLPHOOK_FUN_DRAWITEMSCOLLECTION_HH


class DrawItemsCollection {

};


#endif //GOLPHOOK_FUN_DRAWITEMSCOLLECTION_HH
